debionetwork/debio-frontend

src/lib/polkadotProvider/command/orders.js
src/router/routes/lab.js
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

- Use order_id as param to fulfill order
- Use order_id as route param in Order Process page

Fix fulfill order not working

---

src/lib/polkadotProvider/command/labs/index.js
src/lib/polkadotProvider/query/services.js
src/store/substrate/types.json
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-402?atlOrigin=eyJpIjoiMWE5MzQ1ZGMzMjM3NGE1ZThmYmEzN2Q1N2IyMGY2YTAiLCJwIjoiaiJ9
Update services query and command
- Updated service query to get `price`
- Added new profile image field in lab registration
- Update `types.json`
- New `CurrencyType` and `DurationType` enum added to `types.json`.

feat: updated the services query (DBIO-402).

---

src/views/Dashboard/Customer/RequestTest/index.vue

Fix services not displaying in request test page

fix: Fix services query

---

build-dev.sh
reload-dev.sh
reload_fronted_dev.sh

- Use asia.gcr.io/degenics docker registry
- Rename reload_fronted_dev.sh -> reload-dev.sh

ci: Update deployment scripts

---

src/lib/polkadotProvider/command/geneticTesting.js
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetworkSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-249?atlOrigin=eyJpIjoiMWE5MzQ1ZGMzMjM3NGE1ZThmYmEzN2Q1N2IyMGY2YTAiLCJwIjoiaiJ9
Every step in lab supposed to be save in status
- Save progress after QC and Wetwork.

feat: save lab process order progress (DBIO-249).

---

src/views/Dashboard/Customer/RequestTest/FindLab.vue

- change prices property to price_components when querying for services

fix: Fix Services not displaying on screen

---

package-lock.json
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-407?atlOrigin=eyJpIjoiYjlkNmQzN2I1NTc0NDVjMWIzY2UxOGRkZGZhMTAwZDgiLCJwIjoiaiJ9
Fix Dialog Alert shown ETH is 0, when customer have enough ETH to proceed

fix: fix dialog alert shown ETH is 0 (DBIO-407)

---

src/components/StatusChip.vue
src/constants/specimen-status.js
src/views/Dashboard/Customer/OrderHistoryDetail/Failed.vue
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue

This PR related to this issue on JIRA
https://blocksphere2020.atlassian.net/browse/DBIO-310?atlOrigin=eyJpIjoiZjdlZmVkYWZlZWYyNDAyZjhlYTBjYTExYmZiYjk5ZWUiLCJwIjoiaiJ9
this how its look like

[ New Page ] Order history failed component page

---

src/components/WalletBinding.vue
src/lib/metamask/wallet.js
src/store/metamask/contracts/contract.json
src/store/substrate/types.json

- adjust to change of currency type from Substrate
- Change DAI Address to address in rinkeby network
- handle error on getting ERC20 decimals, default to 18

feat: Update substrate types + fixes

---

src/views/Dashboard/Customer/OrderHistoryDetail/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-468?atlOrigin=eyJpIjoiMzNiNGNkYTYzYmUxNGM3NWExMDNhOWE3ODI2OTFkZjQiLCJwIjoiaiJ9

[ Fix ] Customer checkout loading to order details

---

src/lib/polkadotProvider/query/labs/index.js
src/views/Dashboard/Customer/RequestTest/FindLab.vue

https://blocksphere2020.atlassian.net/browse/DBIO-422?atlOrigin=eyJpIjoiYmU2YmY2NzZiZDI2NGE2OWJlNTc5YmRhYThjY2NmZjgiLCJwIjoiaiJ9
https://blocksphere2020.atlassian.net/browse/DBIO-510?atlOrigin=eyJpIjoiZjBlZTk4YTk2OWY3NDUzYzg2MDZmNmIzNTZkYmVlOWIiLCJwIjoiaiJ9
- Catch error when mapping service data
- Exclude broken service data from services to be rendered

fix: Registered lab not detected, and lab products not showing

---

src/lib/polkadotProvider/command/geneticTesting.js
src/store/index.js
src/store/substrate/types.json
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ComputeSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/GenotypeSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/FileCard.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReviewSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-471?atlOrigin=eyJpIjoiZTJkN2Y5M2FiNWFhNDljOGE0Nzg3NDUzMmFiZjI2ZmQiLCJwIjoiaiJ9
- https://blocksphere2020.atlassian.net/browse/DBIO-412?atlOrigin=eyJpIjoiMTZlYzgwOGVkNTc0NGY0ZDkzMzQxODZiYzA0ZDk0N2EiLCJwIjoiaiJ9
- change and adjust new status name
- adjust specimen number in lab

feat: change status name (dbio-471)

---

.gitignore
package-lock.json
src/views/Dashboard/Customer/RequestTestCheckout/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-404?atlOrigin=eyJpIjoiNzk0NWE3Y2I2NjZkNDMyY2JmYzQ5NDI5NWQwODA2MzAiLCJwIjoiaiJ9
- add button that will directing user to binding wallet when checkout, if wallet has not been connected yet

feat: add link to binding wallet when checkout (DBIO-404)

---

src/components/Stepper/index.vue
src/views/Dashboard/Customer/RequestTest/FindLab.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ComputeSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/GenotypeSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/FileCard.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReviewSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- Fix Lab DNA sample Processing steps
- Use Stepper component for dna sample checklist
- Fix Rejected Sample title and description not showing in Lab dna processing page

fix: Fix Request Test Flow

---

src/lib/faucet.js
src/store/auth/index.js

https://blocksphere2020.atlassian.net/browse/DBIO-516?atlOrigin=eyJpIjoiNzk1OGMyYTAyMzk0NDM0ZWIwMWNkZjE4ODhjNjdiYzgiLCJwIjoiaiJ9
- Fix dev app config to not using DEV web3 RPC

fix: Wallet Binding Wrong RPC

---

src/components/NavigationDrawer.vue
src/router/routes/customer.js
src/router/routes/doctor.js
src/router/routes/hospital.js
src/router/routes/lab.js
src/views/Dashboard/Customer/RequestTest/index.vue

Add customer care link to NavigationDrawer. Opens Gitbook

feat: Customer Care Link

---

src/lib/app-config.js
src/lib/metamask/wallet.js

- Set eth transaction parameters:
- maxFeePerGas: '2000000000',
- maxPriorityFeePerGas: '1000000000',
In order to speed up transaction time

fix: Set eth transaction Gas Priority Fee

---

src/components/OrderCard.vue
src/views/Dashboard/Customer/OrderHistory.vue
src/views/Dashboard/Customer/OrderHistoryDetail/Refund.vue
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue
src/views/Dashboard/Customer/RequestTestReceipt.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-412?atlOrigin=eyJpIjoiYTE5MTJhMWVhYTUzNGQwM2IzMzkxZWZjMDM4YjU5MzkiLCJwIjoiaiJ9
- https://blocksphere2020.atlassian.net/browse/DBIO-505?atlOrigin=eyJpIjoiNzE1ZjE0ZmQ4OTZiNGM4NjhlNTMxZDhkNDk3NjEyM2MiLCJwIjoiaiJ9
- change format specimen number in lab
- change format specimen number in customer

fix: fix specimen number in customer and lab

---

src/components/Dialog/DialogStakingDataConfirmation.vue
src/views/Dashboard/Customer/TestResult/result.vue

https://blocksphere2020.atlassian.net/browse/DBIO-460?atlOrigin=eyJpIjoiNTcxYzU2NjM0ZDQxNGZmMGFlNTgyMjIzY2JhMWZkMmEiLCJwIjoiaiJ9
- disabled button staking data when data staked
- create staking data confirmation dialog

feat: page staking data after success (DBIO-460)

---

src/components/DialogSelectUserLogin.vue

https://blocksphere2020.atlassian.net/browse/DBIO-499?atlOrigin=eyJpIjoiMTM1MzYzMDI2YWMyNDI4ZWEzYzk1MWFjMjkwZDVkM2QiLCJwIjoiaiJ9
- Remove DOT (currency) on balance in login page

fix: remove DOT in login page

---

src/components/ProgressOrderStatus.vue
src/lib/polkadotProvider/query/orders.js
src/views/Dashboard/Lab/Services/index.vue
src/views/Login/LandingDemo.vue

- Show dummy services image as icons
- Fix order duration in customer's order detail
- Add "is not audited" to disclaimer in landing page

fix: Minor Fixes for Demo Prep

---

src/views/Dashboard/Customer/Documents/DocumentResult.vue
src/views/Dashboard/Customer/Documents/DocumentsList.vue
src/views/Login/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-550
https://blocksphere2020.atlassian.net/browse/DBIO-565
- Add tooltip "Under development" on buttons
- Add info on demo lab accounts @ login screen

feat: Demo Prep - Tooltip "Under development", Demo Lab Accounts info

---

src/views/Dashboard/Customer/Documents/DocumentsList.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-554
In Customer Role (Documents):
- Upload an EMR Document → Upload EMR Documents
In Lab Role (Order History)
- Genome has been uploaded → VCF data has been uploaded

Fix: Fix typos (DBIO-554)

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-551?atlOrigin=eyJpIjoiNzkxNTYyMTI0ZGUyNGZmOGE1NDlhMjg5OTFlZjQ5NDgiLCJwIjoiaiJ9
In Lab
- add select component for category in add service page
- add select component for category in detail service page

add service category in lab (DBIO-551)

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

https://blocksphere2020.atlassian.net/browse/DBIO-551?atlOrigin=eyJpIjoiYTUzMTllYmFmMGMxNGJhYTlhZGY3ZWM4NWRhOTIzYzgiLCJwIjoiaiJ9
In categorie list :
whole-Transcriptome Sequencing → Whole-Transcriptome Sequencing

fix: fix typo in list categories

---

src/views/Dashboard/Customer/OrderHistory.vue
src/views/Dashboard/Customer/RequestTest/FindLab.vue
src/views/Dashboard/Customer/RequestTestCheckout/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-519?atlOrigin=eyJpIjoiZDNiYmZjY2ZlYTk1NDAxMmJkZjk3ZDY1MGQ0MTIxNjIiLCJwIjoiaiJ9
- https://blocksphere2020.atlassian.net/browse/DBIO-561?atlOrigin=eyJpIjoiMWJkMDI4ZWIxOTdiNDdkZmFkNjlhMDU3MmZkOWE3MDEiLCJwIjoiaiJ9
- Fix total price on service product
- Fix Missing action button on table listing

Fix: Action Button Cancelled Order, Order full Price

---

Dockerfile.demo
build-demo.sh
package.json
reload-demo.sh
src/components/SetKeystorePasswordDialog.vue
src/store/auth/index.js

- Added Dockerfile.demo
- Added build-demo.sh, reload-demo.sh to build and run docker images in
demo env
- Adjust recaptcha url and SetKeystorePasswordDialog.vue
- Adjust env loading logic in src/store/auth/index.js

ci: Demo Server Requirements

---

src/components/NavigationDrawer.vue
src/router/routes/customer.js
src/views/Dashboard/Customer/Documents/DocumentsList.vue
src/views/Dashboard/Customer/EMR/UploadEMR.vue
src/views/Dashboard/Customer/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-319
https://www.figma.com/file/zl3qPAORY04CoGl1v5gSHw/DeBio-Web-App?node-id=1530%3A0
Minor update some layout on the EMR page
Hi, guys, I have a question, I hope you are can help me, I have no idea to handle this layout. Have you ever got an error when uploading a file directly (pending file)? (before it is sent to the server). I think if I upload files one by one directly to the server without pending files first it's not possible, because on the last step there will be a re-confirmation dialog. And the second problem is if I upload directly to the server is when users refresh the page and they do not confirm the dialog on the last step it will still be uploaded to the server, any idea guys? Thanks in advance

[ Update ] Layout on EMR page

---

src/lib/metamask/mixins/README.md
src/lib/metamask/mixins/serviceHandler.js
src/views/Dashboard/Customer/Documents/DocumentsList.vue
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue
src/views/Dashboard/Customer/RequestTest/FindLab.vue

Add a new service handler specific for metamask

[ Update ] Add new servicehandler

---

src/components/Dialog/ServiceDialog.vue
src/router/routes/customer.js
src/store/lab/index.js
src/views/Dashboard/Customer/RequestTest/FindLab.vue
src/views/Dashboard/Customer/RequestTest/ServiceRequest.vue
src/views/Dashboard/Customer/RequestTest/StakingDialog.vue

https://blocksphere2020.atlassian.net/browse/DBIO-478?atlOrigin=eyJpIjoiMGNmM2UwZjZlMTFiNDFlMGEyMzI2YmI2MDVjYmI3ZGIiLCJwIjoiaiJ9
- Create notification when success request lab staking
- Create page service request

add notification staking success

---

src/components/RatingBox.vue
src/store/feedback/index.js
src/store/index.js
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-538](url)
Set Endpoint to backend for store feedback from customer

Fix: Front End connection to BE for rating after success checkout order

---

package-lock.json
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-469](url)
- When order customer status fulfilled, customer get notification if they got reward 5 DBIO

Feat: Notification incentive when customer test's already fullfiled by lab

---

src/views/Dashboard/Customer/Documents/DocumentsList.vue
src/views/Dashboard/Customer/EMR/UploadEMR.vue

Minor fix and update some unnecessary code

[ Fix ] Bug upload EMR page

---

src/store/lab/index.js
src/views/Dashboard/Customer/RequestTest/ServiceRequest.vue
src/views/Dashboard/Customer/RequestTest/StakingDialog.vue

https://blocksphere2020.atlassian.net/browse/DBIO-592?atlOrigin=eyJpIjoiNDcxNTU0YmUxNDQwNDUwZjllOWRiN2ZiNDFlNzM3NjQiLCJwIjoiaiJ9
Fix staking amount and notification in store and staking dialog.

fix: send service request to transaction to ServiceRequest

---

src/views/Dashboard/Customer/TestResult/result.vue

https://blocksphere2020.atlassian.net/browse/DBIO-602?atlOrigin=eyJpIjoiMjhhNzViMWQzN2VhNDMxY2E5NDU5NTdlZDA0MjQzMjIiLCJwIjoiaiJ9
- show staking option when the category is "WGS"

show staking option when category is wgs (dbio-602)

---

src/views/Dashboard/Customer/RequestTest/FindLab.vue
src/views/Dashboard/Lab/Account/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-679
Update (Customer and Lab) location integration with backend

[Update] Integration locations

---

package-lock.json
src/lib/polkadotProvider/query/geneticTesting.js
src/views/Dashboard/Lab/TestResults.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-564
- Fixed test results not showing in lab dashboard.

fix: test result not showing on lab dashboard.

---

src/lib/polkadotProvider/command/orders.js
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-591
- Saved temporary file upload URLs on the blockchain.
- https://github.com/debionetwork/debio-node/pull/62

fix: saved temp upload URL on blockchain.

---

src/router/routes/customer.js
src/views/Dashboard/Customer/RequestTest/ServiceRequest.vue
src/views/Dashboard/Customer/RequestTest/StakingDialog.vue

https://blocksphere2020.atlassian.net/browse/DBIO-478?atlOrigin=eyJpIjoiN2RhMDc0YzIzMjkyNDg2Mzk2NGQ2OTAyNzAyZTJlY2UiLCJwIjoiaiJ9
- fix page service reqeuest

fix: fix servive category page

---

src/components/SetKeystorePasswordDialog.vue
src/views/Dashboard/Customer/EMR/UploadEMR.vue
src/views/Dashboard/Doctor/Account/Certification.vue
src/views/Dashboard/Doctor/Account/Verification.vue
src/views/Dashboard/Doctor/Registration/index.vue
src/views/Dashboard/Hospital/Account/Certification.vue
src/views/Dashboard/Hospital/Account/Verification.vue
src/views/Dashboard/Hospital/Registration/index.vue
src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/Verification.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-632](url)
Add Validation every input, you can check validation requirement on this file [https://docs.google.com/spreadsheets/d/11_Stik7dVjr1VByIS1raU75xvhTifTxL5HgQw8ybtd4/edit?usp=sharing](url)

Implement Validation

---

src/components/DataTable/ServerSideDataTable/index.vue
src/utils/convertSlug.js
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
src/views/Dashboard/Lab/RequestLab/Mapping/SearchBar.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/regions.json
src/views/Dashboard/Lab/RequestLab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-525
- https://blocksphere2020.atlassian.net/browse/DBIO-526
- https://blocksphere2020.atlassian.net/browse/DBIO-599
- https://blocksphere2020.atlassian.net/browse/DBIO-685
- https://blocksphere2020.atlassian.net/browse/DBIO-675
- Add zoom in function
- Add zoom out function
- Zoom area on search
- Remove the get location button
- Remove select per regions
- Update color/heatmap by the number of requests
- Update page card title
- Update country, state, and city lab register
- Update label lab account from region to state

[ Update Feature ] Map page

---

src/views/Dashboard/Lab/Services/Add.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-632](url)
minor fix on lab/services/add
validation triggered fail after user click add service

Fix: Implement validation

---

src/store/metamask/contracts/contract.json

https://blocksphere2020.atlassian.net/browse/DBIO-594
- Change Service Request Address in store
- Change Escrow Address in store

fix service request and escrow address

---

src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-697
- Encrypt mneumonic saved in localstorage and vuex

Encrypt Mneumonic

---

src/components/DNASampleSendingInstructions.vue
src/lib/polkadotProvider/query/orders.js
src/views/Dashboard/Customer/OrderHistory.vue
src/views/Dashboard/Customer/OrderHistoryDetail/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-520
- https://blocksphere2020.atlassian.net/browse/DBIO-596
- Update search order history API

[ Update ] Search order history API

---

src/store/index.js
src/store/registration/index.js
src/store/substrate/index.js
src/views/Dashboard/Lab/NavigationLayout.vue

https://blocksphere2020.atlassian.net/browse/DBIO-806
-create store for pre-registration
-add  function to get debio in lab dashboard

feat: get debio when login as lab

---

src/store/substrate/types.json

fix: update types.json

---

package-lock.json
src/store/substrate/types.json
src/views/Dashboard/Lab/Services/Add.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-898](url)
- if service type is Biomedical Testing, qc price is disabled and cq price value is zero

fix: Add service Biomedical there is no QC price

---

src/components/HeaderUserInfo.vue
src/store/lab/index.js
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/Services/Add.vue

JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-968
Changelog/Description 🗒️
- Update flow request services

fix: Request service flow

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-998](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-999](url)
- Add new dna_collection_process field in Services registration form.
- Add new dna_collection_process field in Services edit form.

add field for DNA collection process on add service lab

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/mlc_config.json
.github/workflows/publish-draft-release-candidate.yml
.github/workflows/publish-draft-release.yml
.github/workflows/pull-request.yml
.github/workflows/rcb_config.json
.github/workflows/release-candidate.yml
.github/workflows/release.yml
.maintain/docker/Dockerfile

ci: add github action workflow

ci: add github action workflow

---

src/api/service-request.js
src/components/SetKeystorePasswordDialog.vue
src/lib/categories.js
src/lib/polkadotProvider/query/orders.js
src/store/auth/index.js
src/store/lab/index.js
src/store/registration/index.js
src/store/wallet/index.js

JIRA Link
--
Changelog
- renaming all env degenics to debio

fix: renaming env

---

src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1075
- Fixed typo in Lab dashboard to show verified status.

fix: lab verified status.

---

src/lib/polkadotProvider/events/handlers/lab.js
src/lib/polkadotProvider/events/index.js
src/store/substrate/event-types.json
src/store/substrate/index.js
src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1059
- Fix notification is verified.

fix: notification verified.

---

src/views/Dashboard/Lab/Account/Certification.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1083
- Fix showing certification file on edit.

fix: show cert file.

---

src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1070
- Fix lab registration stepper.

fix: lab registration stepper.

---

src/components/DialogSelectUserLogin.vue

###JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-1062
###Changelog
- get account detail from local storage

fix: No Account Shows after logout

---

src/router/routes/customer.js
src/router/routes/doctor.js
src/router/routes/hospital.js
src/router/routes/lab.js

- [[Front End: Lab - Customer Care] Redirect to gitbook](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1091&assignee=6087b822248ef6007372dab6)
- changed link customer care button to gitbook

fix: fixed customer care redirect to gitbook

---

src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/Stepper.vue
src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1070
- Fix lab registration stepper.

fix: stepper wording.

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/mlc_config.json
.github/workflows/publish-draft-release-candidate.yml
.github/workflows/publish-draft-release.yml
.github/workflows/pull-request.yml
.github/workflows/rcb_config.json
.github/workflows/release.yml
.maintain/docker/Dockerfile

ci: added github workflows

---

src/components/DialogSelectUserLogin.vue
src/components/HeaderUserInfo.vue
src/lib/balance-format.js
src/lib/polkadotProvider/query/balance.js
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1148
- adjust prices to and from ether format

change price/currency to and from ether format

---

src/components/DialogSelectUserLogin.vue
src/components/HeaderUserInfo.vue
src/lib/balance-format.js
src/lib/polkadotProvider/query/balance.js
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/index.vue

Co-authored-by: ciniiia <cinia@blocksphere.com>

Merge PR by debio-toolkit

---

.github/workflows/alpha.yml

ci: separate staging ssh

---

src/views/Dashboard/Lab/Services/Detail.vue

- Add format to ether in edit service

fix: bugs in edit service

---

src/router/routes/lab.js
src/views/Dashboard/Lab/LabOrders.vue
src/views/Dashboard/Lab/OrderHistory/index.vue
src/views/Dashboard/Lab/TestResults.vue

[[Front End: Lab - Dashboard] Wrong name & redirection](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1078&assignee=6087b822248ef6007372dab6)
- fixed redirect button and wording Lab - Dashboard
- fixed code indentation

fix: fixed redirect button and wording Lab - Dashboard

---

src/components/DataTable/ServerSideDataTable/index.vue
src/lib/polkadotProvider/command/services.js
src/lib/services.js
src/store/substrate/index.js
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/RequestLab/index.vue
src/views/Dashboard/Lab/Services/Add.vue

https://blocksphere2020.atlassian.net/browse/DBIO-851
Update request service flow lab

feat: Request service lab

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReceiveSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
src/views/Dashboard/Lab/OrderHistory/index.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/views/Dashboard/Lab/result.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-848](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-897](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-899](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-998](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-999](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-1084](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-1206](url)

fix: fix lab service process sample

---

src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Services/Add.vue

URL to your task/ticket number in JIRA (if applicable)
https://blocksphere2020.atlassian.net/browse/DBIO-1085
The description of your task or what is changed.
- Fix disabled service category
- Create a new prompt design for delete lab certification

fix: Disabled service category and add new prompt for certification

---

.eslintignore
src/lib/orders.js
src/views/Dashboard/Lab/OrderHistory/index.vue

URL to your task/ticket number in JIRA (if applicable)
- https://blocksphere2020.atlassian.net/browse/DBIO-1240
- https://blocksphere2020.atlassian.net/browse/DBIO-1088
- Fix lab search order pagination issue
- Create linter ignore

fix: Lab search order

---

src/views/Dashboard/Customer/index.vue
src/views/Dashboard/Doctor/NavigationLayout.vue
src/views/Dashboard/Hospital/NavigationLayout.vue
src/views/Dashboard/Lab/NavigationLayout.vue

[[Front End: Customer - Header] Logo DeBio wrong redirection](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1189&assignee=6087b822248ef6007372dab6)
- fix: fixed link on debio's logo

fix: fixed link on debio's logo

---

src/components/HeaderUserInfo.vue
src/lib/polkadotProvider/events/handlers/lab.js
src/lib/polkadotProvider/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1193
- fix price format in  notification
- fix price format in lab navbar

fix: fix price format

---

src/views/Dashboard/Lab/OrderHistory/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-1081
- Fix naming in action button (Payment History)

fix: naming on action button

---

src/views/Dashboard/Lab/OrderHistory/index.vue

fix: adjust variabel

---

src/views/Dashboard/Lab/OrderHistory/index.vue

fix: fix bugs route in action button

---

src/views/Dashboard/Lab/OrderHistory/index.vue

- Adjust status
- Adjust naming action button

fix: adjust naming status and button

---

src/views/Dashboard/Lab/Services/Add.vue

[Front End: Lab - Add Service] Several issues on add [service](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1261&assignee=6087b822248ef6007372dab6)
The description of your task or what is changed.
- fix create service validation and loading

fix create service validation

---

src/components/HeaderUserInfo.vue
src/components/WalletBinding.vue
src/lib/location.js
src/store/feedback/index.js
src/store/substrate/index.js
src/store/wallet/index.js
src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
src/views/Dashboard/Lab/RequestLab/Mapping/SearchBar.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1155
- https://blocksphere2020.atlassian.net/browse/DBIO-1207
- https://blocksphere2020.atlassian.net/browse/DBIO-1279
- Fix wallet binding unclickable
- Fix mismatch endpoint location
- Fix notification lab register verification
- Fix register button disappear
- Fix requests service sorting data
- Fix tooltip not shown on request service
- Update wording currency

fix: Some lab issue

---

src/lib/polkadotProvider/query/orders.js
src/views/Dashboard/Lab/LabOrders.vue
src/views/Dashboard/Lab/TestResults.vue
src/views/Dashboard/Lab/index.vue

[Front End: Lab - Dashboard] Inconsistence number of [cards](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1089&assignee=6087b822248ef6007372dab6)
- fix: fixed Inconsistence number of cards

fix: fixed Inconsistence number of cards

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

[[Front End: Lab - Process Order] Status on order details and order table listing not matched](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1077&assignee=6087b822248ef6007372dab6)
- fix: fixed status on order details and order table listing not matched
- fixed indentation 2 spaces

fix: fixed status on order details and order table listing not matched

---

src/lib/location.js
src/store/feedback/index.js

fix: base url

---

src/store/substrate/event-types.json

fix: Add event types

---

src/views/Dashboard/Lab/RequestLab/Mapping/SearchBar.vue
src/views/Dashboard/Lab/Services/Add.vue

NA
- Update service add validation
- Fix Search bar

fix: Request map and update validation

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue

-
- fix: fixed validation services in registration

fix: fixed validation services

---

src/views/Login/index.vue

N/A
- Remove demo labs accounts options

refactor: Remove demo labs options

---

src/lib/polkadotProvider/events/handlers/lab.js
src/store/substrate/event-types.json

N/A
- Minor fix wallet binding notification

fix: Notification wallet binding

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/index.vue

N/A
- Fix several issue on service page

fix: Several issue on service page

---

src/components/SetKeystorePasswordDialog.vue
src/views/Login/index.vue

- none
- deleted component popup demo version on landing page leb(customer old)
- deleted unused console.log on SetKeystorePasswordDialog

fix: deleted popup

---

src/components/HeaderNotification.vue
src/lib/polkadotProvider/events/handlers/lab.js
src/router/routes/lab.js
src/store/substrate/event-types.json
src/store/substrate/index.js
src/views/Dashboard/Lab/Services/Detail.vue
src/views/Dashboard/Lab/Services/index.vue

NA
Update wiring
Fix fetching and delete service loading

fix: Delete and fetching service and update wiring notification

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

[Front End: Lab - Process Order Stepper process not match with Figma](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1076&assignee=6087b822248ef6007372dab6)
- fixed stepper process status

fix: fixed stepper process status

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Detail.vue

N/a
- Fix price format in detail service
- Fix price variable

fix: price format and variable

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

ci: update env

---

src/lib/polkadotProvider/events/handlers/lab.js
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue

N/A
- Update value dai to dbio

fix: Request service and update notification

---

.maintain/docker/build-image.sh
.maintain/docker/create-network.sh
.maintain/docker/docker-compose.yml
.maintain/docker/start-docker-compose.sh
.maintain/docker/stop-docker-compose.sh
nginx/conf.d/default.conf

N/A
add docker maintain scipts

ci: add docker maintain scipts

---

src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue

fix: Zoom australia map

---

src/views/Dashboard/Lab/OrderHistory/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-1366
- Fix orders not show

fix: Orders not show

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1367
- Fix Disabled value
- Fix Price format

fix: Price format

---

src/router/routes/auth.js
src/router/routes/customer.js
src/router/routes/doctor.js
src/router/routes/hospital.js
src/router/routes/index.js
src/router/routes/lab.js
src/router/routes/requestService.js

- N/A
- Refactor path to vue relative path

refactor: path to vue relative path

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

https://blocksphere2020.atlassian.net/browse/DBIO-1386
add new env and fix mainnet secret

ci: add new env and fix mainnet secret

---

src/components/SetKeystorePasswordDialog.vue
src/lib/api/index.js
src/store/feedback/index.js
src/store/registration/index.js
src/store/wallet/index.js

N/A
- Fix update basic auth to general

fix: Update basic auth to general

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

[Front End: Lab - Process Order Status on order details and order table listing not matched](https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1077&assignee=6087b822248ef6007372dab6)
- fixed wording

fix: fixed prompt, button wording

---

src/views/Login/index.vue

Remove unnecessary text

---

src/views/Dashboard/Lab/Registration/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1359](url)
- change function setEthAddress on regis lab. prevent metemask to popup after regis button clicked

fix: fix metemask popup

---

src/components/GenerateAccountDialog.vue
src/components/SecretBackupPhraseDialog.vue
src/store/substrate/index.js
src/views/Dashboard/Lab/NavigationLayout.vue

N/A
- remove substrate console

fix: Remove substrate console

---

src/router/routes/lab.js

https://blocksphere2020.atlassian.net/browse/DBIO-1370
- Fix menu access

fix: Menu access

---

src/lib/api/lab.js
src/views/Dashboard/Lab/Registration/Services/List.vue
src/views/Dashboard/Lab/Registration/Services/index.vue

- N/a
- Enhance post send email when lab registered
- Adjust format price in list service

feat: add endpoint to send email after lab registered

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

N/A
ci: improve high availability

ci: improve high availability

---

.github/workflows/alpha.yml
.github/workflows/release.yml

URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.
The description of your task or what is changed.
e.g: Update substrate config, new feature / bugfix, etc.

ci: update release deployment

---

src/views/Dashboard/Lab/Registration/Services/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1361](url)
- fix bug on selec working days option on regis create service

fix: fix bug working days

---

package-lock.json
package.json
src/lib/api/index.js
src/main.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1421
- Setup app analytics with Mixpanel.
- Sentry for crashlytics.
- Must add `VUE_APP_SENTRY_DSN` and `VUE_APP_MIXPANEL_TOKEN` environment variable, accessible here: https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV

feat: mixpanel and sentry analytics.

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

N/A
improve replicas of deployments and update image pull policy

ci: improve replicas of deployments

---

src/components/UnlockWalletDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1454
- Remove cancel button
- Fix input password on key up enter

[DBIO-1454] fix: remove cancel button on the input password.

---

src/views/Dashboard/Lab/Services/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1090](url)
- remove sorting on image column
- make default data sorting by name (ascending)

[DBIO-1090] fix: remove sorting on image column

---

src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1368
- Change button to clickable icon, in service data table

[DBIO-1368] fix: missing action button in service table

---

src/views/Dashboard/Lab/Registration/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1413](url)
- fix bug validation rules on upload profile on lab registration page

[DBIO-1413] fix: wrong validation error in profile image upload

---

src/components/DialogSelectUserLogin.vue
src/components/HeaderUserInfo.vue
src/components/SetKeystorePasswordDialog.vue
src/lib/local-storage.js
src/router/routes/lab.js
src/store/ethereum/contracts/index.js
src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1495
- Update local storage naming
- Fix lost mnemonic
- Fix duplicate account Keystore
- Fix route validation

[DBIO-1495] fix: logic login with existing account and update localstorage naming

---

src/components/DialogSelectUserLogin.vue
src/components/MenuCard/EnabledMenuCard.vue
src/components/MenuCard/index.vue
src/components/UnlockWalletDialog.vue
src/lib/functions.js
src/router/routes/lab.js
src/views/Dashboard/Lab/index.vue
src/views/Login/index.vue

https://blocksphere2020.atlassian.net/browse/DBIO-1517
- Remove import Keystore
- Add forgot password
- Fix navigation guard
- Fix card redundant router

[DBIO-1517] feat: forgot password and remove import keystore files

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1440
- Fix upload file format
- Update error wording

[DBIO-1140] fix: Several issue on service page

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

add new env

---

src/views/Dashboard/Lab/Account/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1350](url)
-add condition if account lab status verified. lab only change profile picture, email, phone number and web address

[DBIO-1350] fix: lab cannot change address if status Verified

---

src/views/Login/index.vue

N/A
- Minor fix update forgot password

fix: Forgot password

---

src/lib/api/orders.js
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1571
- [DBIO-1571] Change escrow address from ethSellerAddress to debioEscrowAddress
[DBIO-1571]: https://blocksphere2020.atlassian.net/browse/DBIO-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DBIO-1571] Change Escrow Address

---

src/lib/api/services.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1621
- Adjust endpoint for provide service request

[DBIO-1621] adjust endpoint for provide service request

---

src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1637
-Fix a Build bug

[DBIO-1637] fix: Build bug

---

src/lib/api/service-request.js
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1560
- Fix validation input

fix: fix input validation

---

src/App.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/views/LoadingScreen.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1555
- Add a new loading screen
- Update 404 File naming
-

[DBIO-1555] feat: loading screen. 

---

src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1649
- fix: Svg global map error

[DBIO-1649] fix: Svg global map error

---

src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/Registration/Certification.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

fix: english validations.

---

src/lib/ipfs.js
src/views/Dashboard/Doctor/Account/Certification.vue
src/views/Dashboard/Doctor/Registration/index.vue
src/views/Dashboard/Hospital/Account/Certification.vue
src/views/Dashboard/Hospital/Account/index.vue
src/views/Dashboard/Hospital/Registration/index.vue
src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Certification.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/web-workers/ipfs-worker/ipfsWorker.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1666
- Update ipfs flow
-

[DBIO-1666] feat: Keep ipfs file name

---

.github/workflows/tester.yml

Improve tester

---

src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1768
- Refactor code for get publicKey on lab registration
-

[DBIO-1768] Fix: Few issues on step 1 registration

---

.github/workflows/deployer.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-1781
- add nodeSelector to deployment
-

[DBIO-1781] ci: add nodeSelector to deployment

---

src/components/DataTable/index.vue
src/views/Dashboard/Lab/Registration/Certification.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1266](url)
- add popup modal for confirmation on delete certification
-

[DBIO-1266] Chore: add dialog confirmation on delete ceretification

---

src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1666
- Minor fix ipfs name file
-

[DBIO-1666] fix: Minor fix ipfs name file

---

src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1639
- fix loading & disable button submit service
-

[DBIO-1639] fix: loading & disable button submit service

---

src/lib/api/service-request.js
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/RequestLab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1814
- N/A
- fix pagination table request service
-

[DBIO-1814] fix: pagination tabel detail request service

---

.github/workflows/deployer.yml

- N/A
- optimize deployment resource request & limit
-

ci: optimize deployment resource request & limit

---

src/store/index.js
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2078
- take out get-dbio-pre-register
-

[DBIO-2078] refactor: take out get-dbio-pre-register

---

src/views/Dashboard/Lab/RequestLab/Mapping/SearchBar.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2149
- Fix button details view
-

[DBIO-2149] fix: Button details view

---

src/views/Dashboard/Lab/LabOrders.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2316
- https://blocksphere2020.atlassian.net/browse/DBIO-2327
- update filter data shon in order & dashboard page
-

fix: update filter data show

---

src/lib/pinata-proxy.js

- N/A
- Update the pinata gateway link with ENV
-

refactor : Update the pinata gateway link with ENV

---

src/lib/polkadotProvider/events/handlers/lab.js
src/lib/polkadotProvider/events/index.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2226
- N/A
- enhance lab notification
-

fix: enhance lab notification

---

jest.config.js
package-lock.json
src/views/Dashboard/Breadcrumbs.vue
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/file-card.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/quality-control-specimen.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/receive-specimen.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/wetwork-specimen.spec.js
tests/unit/views/Dashboard/Lab/OrderHistory/index.spec.js
tests/unit/views/Dashboard/Lab/Registration/Services/index.spec.js
tests/unit/views/Dashboard/Lab/Registration/Services/list.spec.js
tests/unit/views/Dashboard/Lab/Registration/certification.spec.js
tests/unit/views/Dashboard/Lab/Registration/index.spec.js
tests/unit/views/Dashboard/Lab/Registration/stepper.spec.js
tests/unit/views/Dashboard/Lab/Registration/verification.spec.js
tests/unit/views/Dashboard/Lab/index.spec.js
tests/unit/views/Dashboard/Lab/lab-orders.spec.js
tests/unit/views/Dashboard/Tests/index.spec.js
tests/unit/views/Dashboard/breadcrumbs.spec.js
tests/unit/views/Dashboard/index.spec.js
tests/unit/views/Login/about-us.spec.js
tests/unit/views/Login/index.spec.js
tests/unit/views/Login/landing-demo.spec.js
tests/unit/views/SelectRole/index.spec.js
tests/unit/views/loading-screen.spec.js

-   https://blocksphere2020.atlassian.net/browse/DBIO-2426
-   https://blocksphere2020.atlassian.net/browse/DBIO-2274
-   https://blocksphere2020.atlassian.net/browse/DBIO-2273
-   https://blocksphere2020.atlassian.net/browse/DBIO-2272
-   https://blocksphere2020.atlassian.net/browse/DBIO-2271
-   https://blocksphere2020.atlassian.net/browse/DBIO-2270
-   https://blocksphere2020.atlassian.net/browse/DBIO-2269
-   https://blocksphere2020.atlassian.net/browse/DBIO-2268
-   https://blocksphere2020.atlassian.net/browse/DBIO-2260
-   https://blocksphere2020.atlassian.net/browse/DBIO-2259
-   https://blocksphere2020.atlassian.net/browse/DBIO-2258
-   https://blocksphere2020.atlassian.net/browse/DBIO-2257
-   https://blocksphere2020.atlassian.net/browse/DBIO-2256
- …

tests: lab dashboard and login basic page unit tests

---

src/views/Dashboard/Lab/Registration/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1624
- add validation on file input
-

fix: add validation on file input

---

src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2454
- add note service charge for payment
-

feat: add note service charge for payment

---

src/views/Dashboard/Lab/LabOrders.vue
src/views/Dashboard/Lab/OrderHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2316
- https://blocksphere2020.atlassian.net/browse/DBIO-2327
- update condition status
-

fix: change status condition to show

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue

- N/A
- fix: add note service charge for payment in regist
-

fix: add note service charge for payment in regist

---

src/components/AccessAccountMnemonicDialog.vue
src/components/DialogSelectUserLogin.vue
src/components/SetKeystorePasswordDialog.vue
src/constants/rules.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1672
- update error password & mnemonic wording
- update password validation
-

fix: update error password & mnemonic wording, enhance password validation

---

src/views/Dashboard/Lab/Registration/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1624
- fix validation
-

fix: validation on upload sample result

---

src/lib/api/index.js

- N/A
- update condition handle error from api
-

fix: update condition handle general error

---

src/components/HeaderUserInfo.vue
src/views/Dashboard/Lab/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1824
- Add phone code field
- Fix dummy image
-

fix: missing phonecode

---

src/views/Dashboard/Lab/Registration/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2233
- Fix Lost value after submit
-

fix: Lost value after submit

---

src/components/DialogSelectUserLogin.vue
src/components/UnlockWalletDialog.vue
src/components/VerifyRecoveryPhraseDialog.vue
src/constants/error-messages.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1672
- https://blocksphere2020.atlassian.net/browse/DBIO-1667
- enhance mnemonic & password validation
-

fix: enhance mnemonic & password validation

---

src/lib/pinata-proxy.js
src/lib/polkadotProvider/command/geneticTesting.js
src/lib/polkadotProvider/command/labs/certifications.js
src/lib/polkadotProvider/command/labs/index.js
src/lib/polkadotProvider/command/orders.js
src/lib/polkadotProvider/command/services.js
src/store/substrate/index.js
src/utils/debounce/general/index.js
src/utils/debounce/index.js
src/utils/debounce/substrate/index.js
src/utils/index.js
src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/LabOrders.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReceiveSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
src/views/Dashboard/Lab/Registration/Certification.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1527
- add command for tx weight
- handle fee on registration flow
- handle fee on account
- handle fee on service
- handle fee on order process
- fix indentation
- fix error on get mnemonic data
- add progressEvent on pinata proxy
- add certifications on event listener
- fix button loading
-

feat: add tx weight on lab

---

src/components/Dialog/DialogDeleteConfirmation.vue
src/views/Dashboard/Lab/Registration/Services/List.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1528
- delete service dialog when lab registration
-

feat: dialog delete service when regist

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

- N/A
- minor fix encryption
-

fix: Minor fix encryption

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue

fix: stake lab

---

src/router/routes/lab.js
src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2453
- enhance flow staking lab
-

fix: enhance flow staking lab

---

src/components/Dialog/DialogStake.vue
src/router/routes/lab.js
src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/index.vue

- 
- staking amount not found
-

fix: condition if insufficient balance

---

src/components/HeaderWallet.vue
src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2503
- fix watch balance on wallet header
- n/a

fix: watch wallet balance

---

src/components/Dialog/DialogStake.vue
src/views/Dashboard/Lab/Registration/Services/index.vue

- N/A
- redirect to dashboard after staking
-

Fix : redirect stake dialog

---

src/router/routes/lab.js
src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/index.vue

- N/A
- fix dashboard status condition
- dispatch lab account after staking
-

fix : Staking lab

---

src/views/Dashboard/Lab/Account/Certification.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2428
- disabled Delete certification
-

fix: Disabled Delete certification

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/FileCard.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2470
- Add validation upload result
- fix limit char name
-

fix: Add validation result upload

---

src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2427
- Certificate is mandatory when registration
-

feat : Certificate is mandatory when registration

---

src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Certification.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2232
- add disable on forms / fields
- n/a

fix: disable fields when loading

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2213
- fix validation on reject specimen dialog
n/a
n/a

fix: validation on reject specimen dialog

---

src/constants/error-messages.js

- N/A
- update wording rules password handler
-

fix: rules password handlers

---

src/components/MnemonicTextbox.vue
src/components/VerifyRecoveryPhraseDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2527
- Improve mnemonic verify
-

feat: Improve mnemonic verify

---

src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2543
- Update phonecode rules
-

fix: Remove phone limit validation

---

src/components/OrderList.vue
src/router/routes/lab.js
src/views/Dashboard/Lab/OrderHistory/index.vue
src/views/Dashboard/Lab/index.vue
tests/unit/views/Dashboard/Lab/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2471
- enhance dashboar page 
- fix unit test dashboard
-

feat: order list lab dashboard

---

src/components/WalletBinding.vue
src/lib/metamask/wallet.js
src/views/Dashboard/Lab/Services/Add.vue

- N/A
- Update duration type
-

fix: Minor update duration type

---

.github/workflows/builder.yml
.github/workflows/deployer.yml
.github/workflows/tester.yml

- N/A
- ci: use wlif for gcr auth
-

ci: use wlif for gcr auth

---

src/components/NavigationDrawer.vue
src/router/routes/lab.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1828
- Refactor route
- Update validation menu access
-

fix: Drawer Menu Access

---

src/lib/pinata-proxy.js
src/router/routes/lab.js
src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Services/List.vue
src/views/Dashboard/Lab/Registration/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2427
- Update validation via route for a registration certificate is mandatory
- Add required metadata to Pinata for bulk delete documents that are within the scope of development
- Please frontend add new ENV https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV

fix: Update validation via route

---

package-lock.json
package.json
src/lib/api/index.js
src/main.js
src/plugins/debionetwork-ui-components.js
src/router/routes/lab.js
src/views/maintenancePageLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2578
- Init maintenance page
- Add maintenance handler
-

feat: Add maintenance page

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2592
- Fix stepper upload result status
-

fix: Stepper upload result

---

src/components/VerifyRecoveryPhraseDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2597
- Improve mnemonic logic
-

fix: Handle hidden double word

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

- N/A
- Add vcf mime type to validation rules
-

fix: add vcf mime type

---

src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2631
- Update styling dao maps
-

fix: sub data not show

---

src/components/HeaderNotification.vue
src/components/HeaderWallet.vue
src/components/WalletBinding.vue
src/lib/metamask/index.js
src/store/substrate/index.js
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2528
- https://blocksphere2020.atlassian.net/browse/DBIO-2535
- https://blocksphere2020.atlassian.net/browse/DBIO-2552
- add validation to binding wallet on "register now" button
- handle unavailable city and region on lab registration
- fix bugs on metamask wallet header
- n/a

fix: enhance metamask wallet and some bugs on registration

---

src/components/NavigationDrawer.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2632
- Update table spacing
- Fix the navigation active menu
-

fix: Drawer navigation active menu

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

- N/A
- Update mime type for VCF file
-

fix: VCF mime type update

---

src/components/Button.vue
src/components/Dialog/index.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2591
- Improve the button component
- Improve the dialog component
- Add validation delete service if has an active orders
-

feat: Validation active order

---

src/components/SetKeystorePasswordDialog.vue
src/store/substrate/index.js
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2546
- fix unlock wallet dialog
- fix missing address when reload page
- n/a

fix: fetch polkadot address 

---

src/lib/api/conversion.js
src/lib/api/index.js
src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1665
- https://blocksphere2020.atlassian.net/browse/DBIO-2231
- Fix dropdown menu position
- Tidy up code
- Update dropdown option
-

fix: Dropdown menu and update dropdown value

---

src/components/Dialog/SwitchNetwork.vue
src/components/WalletBinding.vue
src/lib/metamask/index.js
src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1262
- https://blocksphere2020.atlassian.net/browse/DBIO-2528
- fix metamask on register
- add switch network
- n/a

feat: add switch network

---

src/lib/pinata-proxy.js
src/views/Dashboard/Lab/Account/Certification.vue
src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/Registration/Certification.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-851
- Add file size metadata to the pinata
- Update fix request service country code
-

fix: Request service country code and update pinata metadata

---

src/lib/polkadotProvider/events/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2502
- Fix notification validation input
-

fix: Notification validation

---

src/lib/api/dna-collection-process.js
src/lib/api/index.js
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2589
- add endpoint dna-collectio-process
-

feat: add endpoint dna-collection-process

---

src/views/Dashboard/Lab/NavigationLayout.vue
src/views/Dashboard/Lab/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2486
- update method in laseventData listener
-

fix: wording submit verification submitted

---

src/components/HeaderUserInfo.vue
src/lib/api/index.js
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2578
- Fix error response and update popup modal error
-

fix: Popup modal error

---

src/lib/polkadotProvider/events/handlers/lab.js
src/store/substrate/index.js
src/views/Dashboard/Lab/Registration/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2486
- 
- update wording
- handle condition reward

fix: register lab notification

---

src/lib/polkadotProvider/events/handlers/lab.js
src/lib/polkadotProvider/events/index.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2486
- fix duplicat notif & update wording for regist flow notification
-

fix: duplicat notif & update wording for regist flow notification

---

src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReceiveSpecimen.vue
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
src/views/Dashboard/Lab/Registration/Services/List.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2579
- Add insufficient balance popup handler
-

feat: Add popup insufficient balance

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2683
- change max char limit & delete english alphabet validation
-

fix: max char limit & delete english alphabet validation

---

src/lib/polkadotProvider/events/handlers/lab.js
src/lib/polkadotProvider/events/index.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2487
- fix process order flow notification
-

fix: process order flow notification

---

.github/workflows/builder.yml
.github/workflows/create-tags.yml
.github/workflows/deployer.yml
.github/workflows/release.yml
.github/workflows/update-version.yml

- N/A
- update version automation
- code formatting
- Endpoint:
- Scheduler:
- Listener:

ci: update version & formatting

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2761
- putting back english validation
-

fix: long description validation

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2757
- Update claim request service flow
- Update code flow
-

fix: claim request service flow

---

src/views/Dashboard/Lab/Registration/Services/List.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2694
- Popup hide after service succeed deleted
-

fix: Popup hide after service succeed deleted

---

package-lock.json
package.json
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2685
- Update `package.json` and `package-lock.json`
-

fix: Vuetify loading indicator

---

package.json

chore: bump version to 2.0.5

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2725
- Update decimal validation limit on service page
-

fix: Update decimal validation limit

---

src/components/NavigationDrawer.vue
src/router/routes/lab.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2809
- update wording order to order history
-

feat: update wording order to order history

---

src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2811
- update limit validation edit service description
-

fix: limit validation edit service description

---

src/lib/polkadotProvider/events/handlers/lab.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2486
- fix lab regist flow notification
-

fix: lab regist flow notification

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2693
- fix duration validation input with the number only (on service page edit)
- fix location not match sort bug
-

fix: Duration validation input with the number only

---

src/lib/polkadotProvider/events/handlers/lab.js
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2487
- notif finish order from staking request
-

feat: notif finish order from staking request

---

src/components/SetKeystorePasswordDialog.vue
src/components/UserAccountMenu.vue
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2650
- add clear account on sign out
- add clear account on set password
- n/a

feat: add clear account in local storage

---

package-lock.json
package.json
src/components/SetKeystorePasswordDialog.vue
src/components/UserAccountMenu.vue
src/views/Dashboard/Lab/NavigationLayout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2650
- add wallet on set password
- remove all accounts when logout
- n/a

fix: clear account and update version 2.0.6

---

src/components/OrderList.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2866
- rename header table product name to service name
-

fix: rename header table product name to service name

---

src/views/Dashboard/Lab/Account/index.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Registration/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2971
- https://blocksphere2020.atlassian.net/browse/DBIO-2933
- change service category to test category 
- expected duration to maximum duration
- add 
-

feat: enhance lab form

---

src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2971
- set currency default value
-

fix: set currency default value

---

src/utils/env.js

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- fix linter error
-

fix: error linter

---

src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-3023
- fix bugs on connect
-

fix: bugs on connect

---

src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-3023
-  fix can't login from unlock wallet
-

fix: bugs on connection

---

src/lib/notification.js
src/lib/string-format.js
src/store/substrate/index.js
src/utils/referenceFormater.js

- https://blocksphere2020.atlassian.net/browse/DBIO-3023
- https://blocksphere2020.atlassian.net/browse/DBIO-2422
- fix: handle account is null
- add format for reference id
-

fix: handle account is null

---

src/components/HeaderNotification.vue
src/lib/notification.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2422
- fix: set notification read and routes
-

fix: fix set notification read

---

.github/workflows/deployer.yaml
.maintain/docker/entrypoint.sh
README.md

ci: cleanup ssh tunneling

---

src/lib/notification.js

fix: get notif from localStorage
https://blocksphere2020.atlassian.net/browse/DBIO-2422

fix: get notif from localStorage

---

src/lib/notification.js
src/store/substrate/index.js

fix: balance on wallet

---

src/components/HeaderNotification.vue
src/components/HeaderWallet.vue
src/lib/polkadotProvider/query/balance.js
src/store/substrate/index.js

- fix add new state polkadot wallet

fix: wallet usn usdt

---

src/components/DevMenu.vue
src/components/NavigationDrawer.vue
src/components/OrderList.vue
src/router/routes/lab.js

- Enhance wording -> Dashboard to Orders
- Fix order list not shown
- https://blocksphere2020.atlassian.net/browse/DBIO-3145

fix: order list on dashboard

---

src/components/OrderList.vue
src/lib/polkadotProvider/command/service-request.js
src/lib/polkadotProvider/query/service-request.js
src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

- add finalize when order fulfilled
- https://blocksphere2020.atlassian.net/browse/DBIO-3088

feat: Finalize Request when staking

---

src/components/Dialog/DialogStake.vue

- fix check balance in register service form
- https://blocksphere2020.atlassian.net/browse/DBIO-3160

fix: check balance in register service

---

src/views/Dashboard/Lab/Services/Add.vue

- fix conversion from USDT to USD
- https://blocksphere2020.atlassian.net/browse/DBIO-3154

fix: usd rate for conversion from USDT to USD

---

src/views/Dashboard/Lab/Registration/Services/List.vue

- add conversion USDT
- https://blocksphere2020.atlassian.net/browse/DBIO-3141

fix: currency conversion USDT

---

src/components/OrderList.vue

- add rejected status to filter
- https://blocksphere2020.atlassian.net/browse/DBIO-3185

improvement: filter rejected in order table

---

src/views/Dashboard/Lab/Services/Detail.vue

fix render kit link when edit service
- https://blocksphere2020.atlassian.net/browse/DBIO-3021

fix: render kit link when edit service

---

src/components/OrderList.vue
src/views/Dashboard/Lab/LabOrders.vue

- filter Rejected form lab orders
- https://blocksphere2020.atlassian.net/browse/DBIO-3185

fix: filter lab orders

---

src/components/HeaderWallet.vue
src/lib/balance-format.js
src/lib/notification.js
src/views/Dashboard/Lab/Registration/Services/List.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue
src/views/Dashboard/Lab/Services/index.vue

- change payment from USDT to USDT.e
- fix link rules
- https://blocksphere2020.atlassian.net/browse/DBIO-3244
- https://blocksphere2020.atlassian.net/browse/DBIO-3021

feat: change USDT to USDT.e and fix link rules

---

src/views/Dashboard/Lab/Registration/Services/List.vue
src/views/Dashboard/Lab/Registration/Services/index.vue
src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- add label link kit when edit
- fix error to show USDTE price format on register service
- https://blocksphere2020.atlassian.net/browse/DBIO-3021
- https://blocksphere2020.atlassian.net/browse/DBIO-3244

fix: minor bugs in service form

---

src/components/OrderList.vue

- fix filter order and order history
- https://blocksphere2020.atlassian.net/browse/DBIO-3185

fix: filter order list

---

src/components/OrderList.vue

- fix typo status
- https://blocksphere2020.atlassian.net/browse/DBIO-3185

fix: typo status

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue

- change seller address to customer address
- remove unused variables
-https://blocksphere2020.atlassian.net/browse/DBIO-3238

fix: change seller polkadot address to customer polkadot address

---

src/views/Dashboard/Lab/Services/Detail.vue

- fix double label
- https://blocksphere2020.atlassian.net/browse/DBIO-3177

fix: double label

---

src/views/Dashboard/Lab/Services/Add.vue
src/views/Dashboard/Lab/Services/Detail.vue

- check description or long description is hex
- convert description or long description to utf8 if it hex
- convert description or long description to hex when input
- https://blocksphere2020.atlassian.net/browse/DBIO-3177

fix: description and longdescription

---

package.json

chore: remove unused dependecies

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

fix: upload bug

---

src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue

fix: change vcf into raw
